version: '3.8'

services:
  # AI компоненты
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '6.0'

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_HOST=0.0.0.0
    volumes:
      - chroma_data:/chroma/chroma

  # Go сервис для приема данных И анализа
  go-ai-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Для OTLP данных из кластера
      - "8081:8081"  # Для UI/API
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chromadb:8000
      - INTERNAL_API_PORT=8081
      - OTLP_PORT=8080
    depends_on:
      - ollama
      - chromadb
    volumes:
      - ./config:/app/config:ro

  web-ui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data:
  chroma_data: